name: Upload Python Package

on:
  push:
    tags:
      - 'v*.*.*'

permissions:
  contents: read

jobs:
  deploy:
    runs-on: ubuntu-latest
    steps:
    - uses: actions/checkout@v3
    - name: Set up Python
      uses: actions/setup-python@v3
      with:
        python-version: '3.x'
    - name: Install dependencies
      run: |
        python -m pip install --upgrade pip
        pip install -r requirements-dev.txt
    - name: Create regex parser
      run: ./bin/generate.sh
    - name: Run tests
      run: ./bin/run_tests.sh
    - name: Build package
      run: python -m build
    - name: Read version
      run: echo "RELEASE_VERSION=${GITHUB_REF#refs/*/v}" >> $GITHUB_ENV
    - name: Write version to pyproject.toml
      run: |
        echo "Version: $RELEASE_VERSION"
        sed "s/__VERSION__/$RELEASE_VERSION/g" -i pyproject.toml
    - name: Publish package
      uses: pypa/gh-action-pypi-publish@27b31702a0e7fc50959f5ad993c78deac1bdfc29
      with:
        user: __token__
        password: ${{ secrets.PYPI_API_TOKEN }}
